/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Gachapong, GachapongInterface } from "../Gachapong";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_number",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "buyLottery",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "currentLotteryId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentLotteryRound",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "lotteries",
    outputs: [
      {
        internalType: "uint256",
        name: "round",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "number",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610206806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80631398e0761461005157806314b21814146100d95780636be4097c146100f057806384f51869146100f9575b600080fd5b61009e61005f36600461016c565b600260208190526000918252604090912080546001820154928201546003909201549092919073ffffffffffffffffffffffffffffffffffffffff1684565b6040805194855260208501939093529183015273ffffffffffffffffffffffffffffffffffffffff1660608201526080015b60405180910390f35b6100e260005481565b6040519081526020016100d0565b6100e260015481565b61010c610107366004610185565b61010e565b005b60018054600090815260026020819052604082208254815580840186905590810184905560038101805473ffffffffffffffffffffffffffffffffffffffff191633179055825490929091610162836101a7565b9190505550505050565b60006020828403121561017e57600080fd5b5035919050565b6000806040838503121561019857600080fd5b50508035926020909101359150565b60006000198214156101c957634e487b7160e01b600052601160045260246000fd5b506001019056fea26469706673582212206b5d80f78290f4924a7f8c4501c85353084d05ba21da4f18ec6b3eabb4da9f3964736f6c63430008070033";

export class Gachapong__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Gachapong> {
    return super.deploy(overrides || {}) as Promise<Gachapong>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Gachapong {
    return super.attach(address) as Gachapong;
  }
  connect(signer: Signer): Gachapong__factory {
    return super.connect(signer) as Gachapong__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GachapongInterface {
    return new utils.Interface(_abi) as GachapongInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Gachapong {
    return new Contract(address, _abi, signerOrProvider) as Gachapong;
  }
}
