/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ICurrencyManagerInterface extends ethers.utils.Interface {
  functions: {
    "addCurrency(address)": FunctionFragment;
    "isCurrencyWhitelisted(address)": FunctionFragment;
    "removeCurrency(address)": FunctionFragment;
    "viewCountWhitelistedCurrencies()": FunctionFragment;
    "viewWhitelistedCurrencies(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addCurrency", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isCurrencyWhitelisted",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCurrency",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "viewCountWhitelistedCurrencies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewWhitelistedCurrencies",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCurrencyWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewCountWhitelistedCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewWhitelistedCurrencies",
    data: BytesLike
  ): Result;

  events: {};
}

export class ICurrencyManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ICurrencyManagerInterface;

  functions: {
    addCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isCurrencyWhitelisted(
      currency: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    removeCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    viewCountWhitelistedCurrencies(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    viewWhitelistedCurrencies(
      cursor: BigNumberish,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber]>;
  };

  addCurrency(
    currency: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isCurrencyWhitelisted(
    currency: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  removeCurrency(
    currency: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  viewCountWhitelistedCurrencies(overrides?: CallOverrides): Promise<BigNumber>;

  viewWhitelistedCurrencies(
    cursor: BigNumberish,
    size: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string[], BigNumber]>;

  callStatic: {
    addCurrency(currency: string, overrides?: CallOverrides): Promise<void>;

    isCurrencyWhitelisted(
      currency: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    removeCurrency(currency: string, overrides?: CallOverrides): Promise<void>;

    viewCountWhitelistedCurrencies(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewWhitelistedCurrencies(
      cursor: BigNumberish,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[], BigNumber]>;
  };

  filters: {};

  estimateGas: {
    addCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isCurrencyWhitelisted(
      currency: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    viewCountWhitelistedCurrencies(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewWhitelistedCurrencies(
      cursor: BigNumberish,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isCurrencyWhitelisted(
      currency: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    viewCountWhitelistedCurrencies(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewWhitelistedCurrencies(
      cursor: BigNumberish,
      size: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
