name: Test
on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest # macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
      - name: Install dependencies
        working-directory: ./
        run: yarn --frozen-lockfile
      - name: Run tests
        run: npx hardhat test
        env:
          REPORT_GAS: true

  